# TODO: Translation updated at 2026-06-02 13:12

translate french strings:

    # game/options.rpy:15
    old "Come Home"
    new "Come Home"

    # game/options.rpy:35
    old "1.01\n\nReleased (2026-04-24)\n\n- Changed Brandichat from images to screens.\n\n- Changed Polaroid menus to be built in-game instead of pre-made images.\n\n- Improved menu functions to prevent weird rollback issues.\n\n- Made Suzy and Lisa's relationship words more specific - you now specify what the relationship is and how you refer to them as separate things.\n\n- Changed some phone menus to image menus.\n\n- Added sex menus to some characters repeatable sex screens.\n\n- Added four new scenes based off Patreon/Subscribestar polls:\n\n- Added Lisa TV Doggystyle scene\n\n- Added Izzy Anal Missionary scene\n\n- Added Reba Anal Cowgirl scene\n\n- Added Mi-Cha Facefuck Punishment scene\n\n- Fixed some images in the scene where you first have sex with Jez.\n\n- Added 16 new possible combinations for the harem orgy scene.\n\n- Added Chinese and Spanish translations.\n\n- Made it so the \"Telling Suzy\" scene in Lisa's end-game gallery shows up whether you've completed it or not.\n\n- Fixed a bug that would cause Mari's anal scene to play even if you rejected it.\n\n- Various bug fixes.\n\n\n\n\n\n"
    new "1.01\n\nSortie (24/04/2026)\n\n- Remplacement des images par des captures d'écran pour Brandichat.\n\n- Modification des menus Polaroid pour qu'ils soient intégrés au jeu au lieu d'utiliser des images prédéfinies.\n\n- Amélioration des fonctions de menu pour éviter d'étranges problèmes de retour en arrière.\n\n- Précision des termes relatifs à la relation entre Suzy et Lisa : vous pouvez désormais spécifier la nature de la relation et la manière dont vous vous y référez comme des éléments distincts.\n\n- Remplacement de certains menus téléphoniques par des menus d'images.\n\n- Ajout de menus sexuels aux écrans de relations sexuelles répétables de certains personnages.\n\n- Ajout de quatre nouvelles scènes basées sur les sondages Patreon/Subscribestar :\n\n- Ajout de la scène « Lisa TV Doggystyle »\n\n- Ajout de la scène « Izzy Anal Missionary »\n\n- Ajout de la scène « Reba Anal Cowgirl »\n\n- Ajout de la scène « Mi-Cha Facefuck Punishment »\n\n- Correction de certaines images dans la scène où vous avez votre premier rapport sexuel avec Jez.\n\n- Ajout de 16 nouvelles combinaisons possibles pour la scène d'orgie du harem.\n\n- Ajout des traductions en chinois et en espagnol.\n\n- Modification permettant à la scène « Telling Suzy » de la galerie de fin de jeu de Lisa d'apparaître, que vous l'ayez terminée ou non.\n\n- Correction d'un bug qui provoquait la lecture de la scène anale de Mari même si vous l'aviez refusée.\n\n- Diverses corrections de bugs.\n\n\n\n\n\n"

