# TODO: Translation updated at 2026-06-02 13:31

translate german strings:

    # game/options.rpy:15
    old "Come Home"
    new "Come Home"

    # game/options.rpy:35
    old "1.01\n\nReleased (2026-04-24)\n\n- Changed Brandichat from images to screens.\n\n- Changed Polaroid menus to be built in-game instead of pre-made images.\n\n- Improved menu functions to prevent weird rollback issues.\n\n- Made Suzy and Lisa's relationship words more specific - you now specify what the relationship is and how you refer to them as separate things.\n\n- Changed some phone menus to image menus.\n\n- Added sex menus to some characters repeatable sex screens.\n\n- Added four new scenes based off Patreon/Subscribestar polls:\n\n- Added Lisa TV Doggystyle scene\n\n- Added Izzy Anal Missionary scene\n\n- Added Reba Anal Cowgirl scene\n\n- Added Mi-Cha Facefuck Punishment scene\n\n- Fixed some images in the scene where you first have sex with Jez.\n\n- Added 16 new possible combinations for the harem orgy scene.\n\n- Added Chinese and Spanish translations.\n\n- Made it so the \"Telling Suzy\" scene in Lisa's end-game gallery shows up whether you've completed it or not.\n\n- Fixed a bug that would cause Mari's anal scene to play even if you rejected it.\n\n- Various bug fixes.\n\n\n\n\n\n"
    new "1.01\n\nVeröffentlicht (24.04.2026)\n\n- Brandichat wurde von Bildern auf Bildschirme umgestellt.\n\n- Polaroid-Menüs wurden so geändert, dass sie im Spiel erstellt werden, anstatt vorgefertigte Bilder zu verwenden.\n\n- Menüfunktionen verbessert, um seltsame Rollback-Probleme zu verhindern.\n\n- Die Beziehungsbegriffe für Suzy und Lisa wurden präzisiert – du legst nun fest, um welche Beziehung es sich handelt und wie du sie als separate Dinge bezeichnest.\n\n- Einige Telefonmenüs wurden zu Bildmenüs geändert.\n\n- Sexmenüs wurden zu den wiederholbaren Sexbildschirmen einiger Charaktere hinzugefügt.\n\n- Vier neue Szenen hinzugefügt, basierend auf Umfragen bei Patreon/Subscribestar:\n\n- Lisa-TV-Doggystyle-Szene hinzugefügt\n\n- Izzy-Anal-Missionarsstellung-Szene hinzugefügt\n\n- Reba-Anal-Cowgirl-Szene hinzugefügt\n\n- Mi-Cha-Facefuck-Bestrafungsszene hinzugefügt\n\n- Einige Bilder in der Szene korrigiert, in der man zum ersten Mal Sex mit Jez hat.\n\n- 16 neue mögliche Kombinationen für die Harem-Orgie-Szene hinzugefügt.\n\n- Chinesische und spanische Übersetzungen hinzugefügt.\n\n- Es wurde so geändert, dass die „Telling Suzy“-Szene in Lisas Endspiel-Galerie angezeigt wird, unabhängig davon, ob du sie abgeschlossen hast oder nicht.\n\n- Ein Fehler wurde behoben, der dazu führte, dass Maris Anal-Szene abgespielt wurde, auch wenn du sie abgelehnt hast.\n\n- Verschiedene Fehlerbehebungen.\n\n\n\n\n\n"

