# TODO: Translation updated at 2026-06-02 11:43

translate portuguese strings:

    # game/options.rpy:15
    old "Come Home"
    new "Voltar para casa"

    # game/options.rpy:35
    old "1.01\n\nReleased (2026-04-24)\n\n- Changed Brandichat from images to screens.\n\n- Changed Polaroid menus to be built in-game instead of pre-made images.\n\n- Improved menu functions to prevent weird rollback issues.\n\n- Made Suzy and Lisa's relationship words more specific - you now specify what the relationship is and how you refer to them as separate things.\n\n- Changed some phone menus to image menus.\n\n- Added sex menus to some characters repeatable sex screens.\n\n- Added four new scenes based off Patreon/Subscribestar polls:\n\n- Added Lisa TV Doggystyle scene\n\n- Added Izzy Anal Missionary scene\n\n- Added Reba Anal Cowgirl scene\n\n- Added Mi-Cha Facefuck Punishment scene\n\n- Fixed some images in the scene where you first have sex with Jez.\n\n- Added 16 new possible combinations for the harem orgy scene.\n\n- Added Chinese and Spanish translations.\n\n- Made it so the \"Telling Suzy\" scene in Lisa's end-game gallery shows up whether you've completed it or not.\n\n- Fixed a bug that would cause Mari's anal scene to play even if you rejected it.\n\n- Various bug fixes.\n\n\n\n\n\n"
    new "1.01\n\nLançado (24/04/2026)\n\n- Alterou o Brandichat de imagens para ecrãs.\n\n- Alterou os menus Polaroid para serem criados no jogo em vez de imagens pré-criadas.\n\n- Melhorou as funções do menu para evitar problemas estranhos de reversão.\n\n- Tornou as palavras de relacionamento da Suzy e da Lisa mais específicas - agora podes especificar qual é o relacionamento e como te referes a elas como coisas separadas.\n\n- Alterou alguns menus do telefone para menus de imagens.\n\n- Adicionou menus de sexo a ecrãs de sexo repetíveis de algumas personagens.\n\n- Adicionadas quatro novas cenas com base em sondagens do Patreon/Subscribestar:\n\n- Adicionada a cena de Lisa em TV na posição de cãozinho\n\n- Adicionada a cena de Izzy na posição missionária anal\n\n- Adicionada a cena de Reba na posição cowgirl anal\n\n- Adicionada a cena de punição com foda na boca de Mi-Cha\n\n- Corrigidas algumas imagens na cena em que fazes sexo pela primeira vez com a Jez.\n\n- Adicionadas 16 novas combinações possíveis para a cena de orgia do harém.\n\n- Adicionadas traduções para chinês e espanhol.\n\n- Feito com que a cena «Contar à Suzy» na galeria do final do jogo da Lisa apareça, quer a tenhas completado ou não.\n\n- Corrigido um bug que fazia com que a cena anal da Mari fosse reproduzida mesmo que a tivesses rejeitado.\n\n- Várias correções de erros.\n\n\n\n\n\n"

