# TODO: Translation updated at 2026-06-02 09:57

translate russian strings:

    # game/options.rpy:15
    old "Come Home"
    new "Come Home"

    # game/options.rpy:35
    old "1.01\n\nReleased (2026-04-24)\n\n- Changed Brandichat from images to screens.\n\n- Changed Polaroid menus to be built in-game instead of pre-made images.\n\n- Improved menu functions to prevent weird rollback issues.\n\n- Made Suzy and Lisa's relationship words more specific - you now specify what the relationship is and how you refer to them as separate things.\n\n- Changed some phone menus to image menus.\n\n- Added sex menus to some characters repeatable sex screens.\n\n- Added four new scenes based off Patreon/Subscribestar polls:\n\n- Added Lisa TV Doggystyle scene\n\n- Added Izzy Anal Missionary scene\n\n- Added Reba Anal Cowgirl scene\n\n- Added Mi-Cha Facefuck Punishment scene\n\n- Fixed some images in the scene where you first have sex with Jez.\n\n- Added 16 new possible combinations for the harem orgy scene.\n\n- Added Chinese and Spanish translations.\n\n- Made it so the \"Telling Suzy\" scene in Lisa's end-game gallery shows up whether you've completed it or not.\n\n- Fixed a bug that would cause Mari's anal scene to play even if you rejected it.\n\n- Various bug fixes.\n\n\n\n\n\n"
    new "1.01\n\nВыпущено (24.04.2026)\n\n- Изменили Brandichat с изображений на экраны.\n\n- Изменили меню Polaroid, чтобы они создавались в игре, а не были готовыми изображениями.\n\n- Улучшены функции меню, чтобы предотвратить странные проблемы с откатом.\n\n- Сделаны слова, описывающие отношения Сьюзи и Лизы, более конкретными — теперь вы указываете, что это за отношения и как вы относитесь к ним как к отдельным вещам.\n\n- Некоторые телефонные меню заменены на меню с изображениями.\n\n- Добавлены меню секса к повторяемым экранам секса некоторых персонажей.\n\n- Добавлены четыре новые сцены на основе опросов Patreon/Subscribestar:\n\n- Добавлена сцена с Лизой в позе «доги-стайл» на телевизоре\n\n- Добавлена сцена с Иззи в анальной миссионерской позе\n\n- Добавлена сцена с Ребой в анальной позе «наездница»\n\n- Добавлена сцена с Ми-Ча в позе «минет в наказание»\n\n- Исправлены некоторые изображения в сцене, где вы впервые занимаетесь сексом с Джезом.\n\n- Добавлено 16 новых возможных комбинаций для сцены гаремной оргии.\n\n- Добавлены переводы на китайский и испанский языки.\n\n- Сделано так, чтобы сцена «Рассказывая Сьюзи» в галерее финальной части Лизы отображалась независимо от того, прошли вы её или нет.\n\n- Исправлена ошибка, из-за которой анальная сцена с Мари воспроизводилась, даже если вы её отклоняли.\n\n- Различные исправления ошибок.\n\n\n\n\n\n"

